-- Belt or level definitions
CREATE TABLE IF NOT EXISTS belt_levels (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rank INT UNSIGNED NOT NULL,
    description TEXT,
    UNIQUE KEY uniq_belt_rank (rank),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
